### ISSUE TITLE
If user deny's access to contacts

### ISSUE THREAD

**Issue by otymartin** [pavankataria/KPKContacts#1]
Hey, thanks for the resource, really made life easier dealing with the iOS contacts framework :)

My issue is that the user is prompted to grant access to their contact's only once.
IF user later revokes access
THEN this resource has no method to check and alert them to grant access to their device's contacts
IF user does not grant access (I haven't tested this scenario) i'm assuming it won't alert them again next time they load the view attempting to access their contacts.

What I end up with is an empty tableview like below.
![img_3121](https://cloud.githubusercontent.com/assets/2222881/12082201/93462dc6-b25c-11e5-8ed9-803cef68f430.PNG)

**Comment by pavankataria** [comment]
Ok sure, this however is a responsibility on your half. I realise you can't take responsibility because I haven't created the tools to allow you to listen in on these authorization changes.
Thanks for presenting this issue to me on the day you did, I took a look at the post but didn't get time to reply back but I did get time to work on something, you gave me an idea.

So, I've been working on some changes to the demo project as well as the source files over all to add a delegate pattern so you be notified if authorization is disabled when you make a call to the `findContacts...` method.

As shown in the demo project, you can show an alert of some kind.

Here's what I have so far:
![slack_for_ios_upload_1024](https://cloud.githubusercontent.com/assets/1791244/12094448/9dcc57bc-b300-11e5-9544-786e9c9bee73.jpg)

You simply register your class to be the delegate of the KPKContactStore like so:

``` Swift
    kpkContactStore.delegate = self
```

And then adopt the required method to listen to these notifications:

``` swift
    func kpkContactStore(contactStore: KPKContactStore, contactsAccessAuthorizationStatus status: KPKContactAuthorizationStatus) {
        switch status {
            case .Denied:
            // Display alert, .. and so on.
        }
    }
```

How's that? ;)

**Comment by pavankataria** [comment]
All done @otymartin 
Check out these commits: 20893fbbc25dc026b782c413d21e265b907f569c 
latest which includes completion handlers: c3a3f5412be33a56d40fac13fe32f90f4e228ac9

You can check out the demo project and read the readme to see how the delegate method works.
